 

package Forms;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SI
 */
public class DataVendor extends javax.swing.JFrame {
    Connection cn= null;
    ResultSet rs = null;
    DefaultTableModel tabModel;  
    
    public DataVendor() {
        initComponents();
        konek();
        tampilData(); 
    }
 
  
    
            void konek (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection ("jdbc:mysql://localhost/db_multimedia_nusantara","root","");
            Object [] judul_kolom = {"Kode Vendor","Nama Vendor","Alamat","Telepon","Keterangan"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            gridProdi.setModel(tabModel);
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();
    }
  }
    
  
   void tampilData(){
        try{
            Statement stm; //buat stm
            stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("SELECT * FROM t_pabrik ORDER BY kd_pabrik ASC");//mengambil data distributor
            while(rs.next()){
                Object[] data={rs.getString("kd_pabrik"),
                               rs.getString ("nama_pbrk"),
                               rs.getString("alamat"), 
                               rs.getString("telepon"),
                               rs.getString("keterangan"),
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    } 
    
 
    

    int row = 0;
    public void Tampil(){
      row = gridProdi.getSelectedRow();
      kd_pabrik.setText(tabModel.getValueAt(row, 0).toString());
      nama_pbrk.setText(tabModel.getValueAt(row, 1).toString());
      alamat.setText(tabModel.getValueAt(row, 2).toString()); 
      telepon.setText(tabModel.getValueAt(row, 3).toString()); 
      keterangan.setText(tabModel.getValueAt(row, 4).toString());
    }

    public void bersih(){
        kd_pabrik.setText("");
        nama_pbrk.setText("");
        alamat.setText(""); 
        telepon.setText(""); 
        keterangan.setText("");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridProdi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kd_pabrik = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        cmdBaru = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdUpdate = new javax.swing.JButton();
        cmdClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        nama_pbrk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        keterangan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gridProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridProdi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Kode Vendor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Alamat");

        cmdBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add-32.png"))); // NOI18N
        cmdBaru.setText("Refresh");
        cmdBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBaruActionPerformed(evt);
            }
        });

        cmdSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drives-Floppy-icon.png"))); // NOI18N
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Delete-32.png"))); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/door_out.png"))); // NOI18N
        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Telepon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nama Vendor");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Cari Berdasarkan Kode Vendor");

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cari.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Keterangan");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Data Vendor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdBaru)
                        .addGap(10, 10, 10)
                        .addComponent(cmdSimpan)
                        .addGap(6, 6, 6)
                        .addComponent(cmdHapus)
                        .addGap(6, 6, 6)
                        .addComponent(cmdUpdate)
                        .addGap(6, 6, 6)
                        .addComponent(cmdClose)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(3, 3, 3)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCari))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(72, 72, 72)
                            .addComponent(kd_pabrik, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(70, 70, 70)
                                .addComponent(nama_pbrk, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addComponent(kd_pabrik, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addComponent(nama_pbrk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBaru)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdHapus)
                    .addComponent(cmdUpdate)
                    .addComponent(cmdClose)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridProdiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) {
            Tampil();
        }
}//GEN-LAST:event_gridProdiMouseClicked

    private void cmdBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBaruActionPerformed
        // TODO add your handling code here:
        bersih();
}//GEN-LAST:event_cmdBaruActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        // TODO add your handling code here:
        String s_kd_pabrik = kd_pabrik.getText();
        String s_nama_pbrk = nama_pbrk.getText();
        String s_alamat = alamat.getText(); 
        String s_telepon= telepon.getText(); 
        String s_keterangan = keterangan.getText(); 
        
        //validasi isian
        if (s_kd_pabrik.isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Pabrik Masih Kosong");
            kd_pabrik.requestFocus();
            return;
        }
          if (s_nama_pbrk.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Pabrik Masih Kosong");
            nama_pbrk.requestFocus();
            return;
        } 
        if (s_alamat.isEmpty()){
            JOptionPane.showMessageDialog(null,"Alamat Masih Kosong");
            alamat.requestFocus();
            return;
        }
        if (s_telepon.isEmpty()){
            JOptionPane.showMessageDialog(null,"Telepon Masih Kosong");
            telepon.requestFocus();
            return;
        }
        if (s_keterangan.isEmpty()){
            JOptionPane.showMessageDialog(null,"Keterangan Masih Kosong");
            keterangan.requestFocus();
            return;
        }
      
         
                try{
            Statement stm=cn.createStatement();
            stm.executeUpdate("insert into t_pabrik set kd_pabrik='"+s_kd_pabrik+"',"+
                "nama_pbrk='"+s_nama_pbrk+"',"+
                "alamat='"+s_alamat+"',"+ 
                "telepon='"+s_telepon+"',"+ 
                "keterangan='"+s_keterangan+"'");

            tampilData();
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan ");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        }
         
}//GEN-LAST:event_cmdSimpanActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
                try{
            Statement stm=cn.createStatement();
            stm.executeUpdate("DELETE FROM t_pabrik WHERE kd_pabrik='"+
                tabModel.getValueAt(gridProdi.getSelectedRow(),0)+"'");

            tabModel.removeRow(row);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus !");
            bersih();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        // TODO add your handling code here:
        String s_kd_pabrik = kd_pabrik.getText();
        String s_nama_pbrk = nama_pbrk.getText();
        String s_alamat = alamat.getText(); 
        String s_telepon= telepon.getText(); 
        String s_keterangan = keterangan.getText(); 
        
        //validasi isian
        if (s_kd_pabrik.isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Pabrik Masih Kosong");
            kd_pabrik.requestFocus();
            return;
        }
          if (s_nama_pbrk.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Pabrik Masih Kosong");
            nama_pbrk.requestFocus();
            return;
        } 
        if (s_alamat.isEmpty()){
            JOptionPane.showMessageDialog(null,"Alamat Masih Kosong");
            alamat.requestFocus();
            return;
        }
        if (s_telepon.isEmpty()){
            JOptionPane.showMessageDialog(null,"Telepon Masih Kosong");
            telepon.requestFocus();
            return;
        }
        if (s_keterangan.isEmpty()){
            JOptionPane.showMessageDialog(null,"Keterangan Masih Kosong");
            keterangan.requestFocus();
            return;
        }
        
               try{

            Statement stm=cn.createStatement();
            stm.executeUpdate("UPDATE t_pabrik SET kd_pabrik='"
                + s_kd_pabrik + "',nama_pbrk='"
                + s_nama_pbrk + "',alamat='"
                + s_alamat + "',telepon='"
                + s_telepon + "',keterangan='"  
                + s_keterangan +"'where kd_pabrik='"+
                tabModel.getValueAt(gridProdi.getSelectedRow(),0)+"'");
            tampilData();
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error Update");
        }
        
         
    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_cmdCloseActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try{
            Statement stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("select * from t_pabrik where kd_pabrik like '%"+search.getText()+"%'");
            while (rs.next()){
                    Object[] data={rs.getString("kd_pabrik"),
                               rs.getString ("nama_pbrk"),
                               rs.getString("alamat"), 
                               rs.getString("telepon"),
                               rs.getString("keterangan"),

                };
                tabModel.addRow(data);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataVendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton cmdBaru;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JTable gridProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kd_pabrik;
    private javax.swing.JTextField keterangan;
    private javax.swing.JTextField nama_pbrk;
    private javax.swing.JTextField search;
    private javax.swing.JTextField telepon;
    // End of variables declaration//GEN-END:variables

}
