 

package Forms;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat; 
import java.text.SimpleDateFormat; 
 
/**
 *
 * @author SI
 */
public class DataPengeluaran extends javax.swing.JFrame {
    Connection cn= null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    DefaultTableModel tabModel;  
    String tgl; 
    
    public DataPengeluaran() {
        initComponents();
        konek();
        buatnomor();
        sumData();
        tampilData(); 
    }
 
    
            void konek (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection ("jdbc:mysql://localhost/db_multimedia_nusantara","root","");
            Object [] judul_kolom = {"Kode Perangkat","Nama Perangkat","Kuantitas"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            gridProdi.setModel(tabModel);
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();
    }
  }
            
            
            
public void buatnomor(){
        try{
             Statement stm; //buat stm
             stm=cn.createStatement();
            ResultSet rs = stm.executeQuery("SELECT id FROM t_peng ORDER BY id DESC");

            if (rs.next())
            {
                int auto = Integer.parseInt(rs.getString("id")) + 1;
                String auton = "PNG" + auto;
                kode_pengeluaran.setText(auton);
            }
            else{
                String auton = "PNG1";
                kode_pengeluaran.setText(auton);
            }
            rs.close();
        }catch (Exception e){

        }
    }  


     
   void tampilData(){
        try{
            Statement stm; //buat stm
            stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("SELECT * FROM t_detailpengtemp ORDER BY kd_detpengtemp ASC");//mengambil data barang
            while(rs.next()){
                Object[] data={rs.getString("kd_barangtemp"),
                               rs.getString ("nama_barangtemp"),
                               rs.getString("kuantitas"),  
                                
                };  
                tabModel.addRow(data);
            }
            
           
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    }
   
    
    void sumData(){
        try{
         Statement stm3; //buat stm
            stm3=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm3.executeQuery("select sum(kuantitas) from t_detailpengtemp");//mengambil data barang
            rs.next() ; 
            String sum = rs.getString(1);
             txtsum.setText(sum); 
     
        }catch(Exception e){
            e.printStackTrace();
         }  
    }
 
    int row = 0;
    public void Tampil(){
      row = gridProdi.getSelectedRow();
      kd_barang.setText(tabModel.getValueAt(row, 0).toString());
      nama_barang.setText(tabModel.getValueAt(row, 1).toString());  
      kuantitas.setText(tabModel.getValueAt(row, 2).toString());  
    }

    public void bersih(){
        kd_pelanggan.setText("");
        kategori.setText(""); 
        nama_pelanggan.setText("");
        kd_barang.setText("");
        nama_barang.setText(""); 
        kuantitas.setText(""); 

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridProdi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        kd_barang = new javax.swing.JTextField();
        cmdBaru = new javax.swing.JButton();
        cmdTambah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kuantitas = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtsum = new javax.swing.JLabel();
        kd_pelanggan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kode_pengeluaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmdHapus1 = new javax.swing.JButton();
        kategori = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gridProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridProdi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Kode Perangkat");

        kd_barang.setEditable(false);
        kd_barang.setBackground(new java.awt.Color(204, 255, 255));

        cmdBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add-32.png"))); // NOI18N
        cmdBaru.setText("Refresh");
        cmdBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBaruActionPerformed(evt);
            }
        });

        cmdTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drives-Floppy-icon.png"))); // NOI18N
        cmdTambah.setText("Tambahkan");
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        cmdHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Delete-32.png"))); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/door_out.png"))); // NOI18N
        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Kuantitas");

        nama_barang.setEditable(false);
        nama_barang.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nama Perangkat");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtsum.setBackground(new java.awt.Color(0, 153, 153));
        txtsum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        kd_pelanggan.setEditable(false);
        kd_pelanggan.setBackground(new java.awt.Color(204, 255, 255));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Kode Cabang");

        nama_pelanggan.setEditable(false);
        nama_pelanggan.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nama Cabang");

        kode_pengeluaran.setEditable(false);
        kode_pengeluaran.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Kode Pengeluaran");

        cmdHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        cmdHapus1.setText("Simpan");
        cmdHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapus1ActionPerformed(evt);
            }
        });

        kategori.setEditable(false);
        kategori.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Kategori");

        tanggal.setBackground(new java.awt.Color(255, 255, 255));
        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Tanggal");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("*Item");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Data Pengeluaran");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Total :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmdBaru)
                        .addGap(6, 6, 6)
                        .addComponent(cmdHapus1)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txtsum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdClose))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kode_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kd_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(cmdTambah)
                                .addGap(10, 10, 10)
                                .addComponent(cmdHapus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel5)))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(kd_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(kode_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(kd_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(kd_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addComponent(kuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBaru)
                    .addComponent(cmdHapus1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtsum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmdClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridProdiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) {
            Tampil();
        }
}//GEN-LAST:event_gridProdiMouseClicked

    private void cmdBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBaruActionPerformed
        // TODO add your handling code here:
        bersih();
}//GEN-LAST:event_cmdBaruActionPerformed

    private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
        // TODO add your handling code here:
        String s_kd_barang = kd_barang.getText();
        String s_nama_barang = nama_barang.getText();  
        
        //PERHITUNGAN
        int s_kuantitas = Integer.parseInt(kuantitas.getText());   
        
        //validasi isian
        if (s_kd_barang.isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Barang Masih Kosong");
            kd_barang.requestFocus();
            return;
        }
          if (s_nama_barang.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Barang Masih Kosong");
            nama_barang.requestFocus();
            return;
        } 
     
  
       try{
           
           //VALIDASI JIKA BARANG SUDAH ADA
            Statement stm; //buat stm
            stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
             rs=stm.executeQuery("SELECT * from t_detailpengtemp");//mengambil data barang
             if (rs.next()){
             String vkd_barangtemp = rs.getString("kd_barangtemp"); 
 
            if (vkd_barangtemp.equals(s_kd_barang)) {  
             JOptionPane.showMessageDialog(null,"Barang sudah ada"); 
             bersih(); 
             return;
             } 
             }
             
           //VALIDASI JIKA BARANG TIDAK CUKUP 
            Statement stm2; //buat stm
            stm2=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
             rs=stm2.executeQuery("SELECT * from t_barang where kd_barang='" + s_kd_barang + "'");//mengambil data barang
             if (rs.next()){
             
            if (Integer.parseInt(rs.getString("stok")) < s_kuantitas) { 
             JOptionPane.showMessageDialog(null,"Barang tidak mencukupi"); 
             bersih(); 
             return;
             } 
             }      
             
             
        }catch(Exception e){
            e.printStackTrace();
                    
        }
           
                try{
            Statement stm=cn.createStatement();
            stm.executeUpdate("insert into t_detailpengtemp set "+
                "kd_barangtemp='"+s_kd_barang+"',"+
                "nama_barangtemp='"+s_nama_barang+"',"+  
                "kuantitas='"+s_kuantitas+"'");
            sumData();
            buatnomor();
            tampilData();
            bersih();
             
             
            //JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan ");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        }
         
}//GEN-LAST:event_cmdTambahActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
                try{
            Statement stm=cn.createStatement();
            stm.executeUpdate("DELETE FROM t_detailpengtemp WHERE kd_barangtemp='"+
                tabModel.getValueAt(gridProdi.getSelectedRow(),0)+"'");

            tabModel.removeRow(row);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus !");
            bersih();
            buatnomor();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_cmdCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      	tPerangkat barang = new tPerangkat();
				barang.setModal(true);
				barang.setVisible(true); 
				kd_barang.setText(barang.skdbarang);
				nama_barang.setText(barang.snama_barang); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      tCabang pelanggan = new tCabang();
				pelanggan.setModal(true);
				pelanggan.setVisible(true); 
				kd_pelanggan.setText(pelanggan.skd_pelanggan);
				kategori.setText(pelanggan.skategori);
                                nama_pelanggan.setText(pelanggan.snama_plngn);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapus1ActionPerformed
             if (tanggal.getDate() != null) {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tgl = format.format(tanggal.getDate()); 
        }
        
    

        //INSERT TEMP
        try{
            Statement stm; //buat stm
            stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("SELECT * FROM t_detailpengtemp ORDER BY kd_detpengtemp ASC");//mengambil data barang
            while(rs.next()){
            
            stm = cn.createStatement();
            String sql = "INSERT INTO t_detailpeng(kd_detpeng,kd_pengeluaran,kd_barang,nama_barang,kuantitas) VALUES('" 
                      + rs.getString("kd_detpengtemp") + "','" 
                      + kode_pengeluaran.getText() + "','" 
                      + rs.getString("kd_barangtemp") + "','"
                      + rs.getString("nama_barangtemp") + "','" 
                      + rs.getString("kuantitas") + "')";
            int done = stm.executeUpdate(sql);
          
         
            //UPDATE STOK
            rs2=stm.executeQuery("SELECT * FROM t_barang where kd_barang='" + rs.getString("kd_barangtemp") + "'");//mengambil data barang
            rs2.next();
            
             String sql2 = "UPDATE t_barang SET stok='" 
                    + (rs2.getInt("stok") - rs.getInt("kuantitas"))  + "' WHERE kd_barang='"
                    + rs.getString("kd_barangtemp") + "'";

             int done2 = stm.executeUpdate(sql2);
 
             
            }
            
                 stm = cn.createStatement();
                stm.executeUpdate("insert into t_peng set kd_pengeluaran='"+kode_pengeluaran.getText()+"',"+
                "kd_pelanggan='"+kd_pelanggan.getText()+"',"+
                "kategori='"+kategori.getText()+"',"+
                "nama_plngn='"+nama_pelanggan.getText()+"',"+ 
                "tanggal='"+tgl+"',"+ 
                "total='"+txtsum.getText()+"'");
            
            
            //DELETE TEMP
             stm = cn.createStatement();
             String sql4 = "DELETE FROM t_detailpengtemp";
             int don4 = stm.executeUpdate(sql4); 
             DefaultTableModel dm = (DefaultTableModel)gridProdi.getModel();
             dm.fireTableDataChanged();
              buatnomor(); 
              sumData();
              tampilData(); 
              bersih(); 
              
             
            bersih();
        }catch(Exception e){
            e.printStackTrace();
                    
        }
       
        
        
    }//GEN-LAST:event_cmdHapus1ActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_tanggalPropertyChange

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBaru;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdHapus1;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JTable gridProdi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategori;
    private javax.swing.JTextField kd_barang;
    private javax.swing.JTextField kd_pelanggan;
    private javax.swing.JTextField kode_pengeluaran;
    private javax.swing.JTextField kuantitas;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_pelanggan;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JLabel txtsum;
    // End of variables declaration//GEN-END:variables

}
