 

package Forms;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SI
 */
public class DataCabang extends javax.swing.JFrame {
    Connection cn= null;
    ResultSet rs = null;
    DefaultTableModel tabModel;  
    
    public DataCabang() {
        initComponents();
        konek();
        tampilData(); 
    }
 
  
    
            void konek (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection ("jdbc:mysql://localhost/db_multimedia_nusantara","root","");
            Object [] judul_kolom = {"Kode Cabang","Kategori Cabang","Nama Cabang","Alamat","Telepon","Keterangan"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            gridProdi.setModel(tabModel);
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();
    }
  }
    
  
   void tampilData(){
        try{
            Statement stm; //buat stm
            stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("SELECT * FROM t_pelanggan ORDER BY kd_pelanggan ASC");//mengambil data pelanggan
            while(rs.next()){
                Object[] data={rs.getString("kd_pelanggan"),
                               rs.getString ("kategori"),           
                               rs.getString ("nama_plngn"),
                               rs.getString("alamat"), 
                               rs.getString("telepon"),
                               rs.getString("keterangan"),
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    } 
    
  

    int row = 0;
    public void Tampil(){
      row = gridProdi.getSelectedRow();
     kd_pelanggan.setText(tabModel.getValueAt(row, 0).toString());
      kategori.setToolTipText(tabModel.getValueAt(row, 1).toString());
      nama_plngn.setText(tabModel.getValueAt(row, 2).toString());
      alamat.setText(tabModel.getValueAt(row, 3).toString()); 
      telepon.setText(tabModel.getValueAt(row, 4).toString()); 
      keterangan.setText(tabModel.getValueAt(row, 5).toString());
    }

    public void bersih(){
        kategori.setToolTipText("");
        kd_pelanggan.setText("");
        nama_plngn.setText("");
        alamat.setText(""); 
        telepon.setText(""); 
        keterangan.setText("");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridProdi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kd_pelanggan = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        cmdBaru = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdUpdate = new javax.swing.JButton();
        cmdClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        telepon = new javax.swing.JTextField();
        nama_plngn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        keterangan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gridProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridProdi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Kode Cabang");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Alamat");

        cmdBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add-32.png"))); // NOI18N
        cmdBaru.setText("Refresh");
        cmdBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBaruActionPerformed(evt);
            }
        });

        cmdSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Drives-Floppy-icon.png"))); // NOI18N
        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Delete-32.png"))); // NOI18N
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/door_out.png"))); // NOI18N
        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Telepon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nama Cabang");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Cari Berdasarkan Kode Cabang");

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cari.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Keterangan");

        kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daerah" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Cabang");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Data Cabang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(603, 603, 603)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnCari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(cmdBaru)
                        .addGap(3, 3, 3)
                        .addComponent(cmdSimpan)
                        .addGap(7, 7, 7)
                        .addComponent(cmdHapus)
                        .addGap(1, 1, 1)
                        .addComponent(cmdUpdate)
                        .addGap(7, 7, 7)
                        .addComponent(cmdClose))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_plngn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kd_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addComponent(kd_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nama_plngn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCari)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBaru)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdHapus)
                    .addComponent(cmdUpdate)
                    .addComponent(cmdClose))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridProdiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1) {
            Tampil();
        }
}//GEN-LAST:event_gridProdiMouseClicked

    private void cmdBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBaruActionPerformed
        // TODO add your handling code here:
        bersih();
}//GEN-LAST:event_cmdBaruActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        // TODO add your handling code here:
        String s_kd_pelanggan= kd_pelanggan.getText();
        String s_kategori = kategori.getSelectedItem().toString();
        String s_nama_plngn = nama_plngn.getText();
        String s_alamat = alamat.getText(); 
        String s_telepon= telepon.getText(); 
        String s_keterangan = keterangan.getText(); 
        
        //validasi isian
        if (s_kd_pelanggan.isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Cabang Masih Kosong");
            kd_pelanggan.requestFocus();
            return;
        }
          if (s_nama_plngn.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Cabang Masih Kosong");
            nama_plngn.requestFocus();
            return;
        } 
        if (s_alamat.isEmpty()){
            JOptionPane.showMessageDialog(null,"Alamat Masih Kosong");
            alamat.requestFocus();
            return;
        }
        if (s_telepon.isEmpty()){
            JOptionPane.showMessageDialog(null,"Telepon Masih Kosong");
            telepon.requestFocus();
            return;
        }
        if (s_keterangan.isEmpty()){
            JOptionPane.showMessageDialog(null,"Keterangan Masih Kosong");
            keterangan.requestFocus();
            return;
        }
      
         
                try{
            Statement stm=cn.createStatement();
            stm.executeUpdate("insert into t_pelanggan set kd_pelanggan='"+s_kd_pelanggan+"',"+
                "kategori='"+s_kategori+"',"+
                "nama_plngn='"+s_nama_plngn+"',"+
                "alamat='"+s_alamat+"',"+ 
                "telepon='"+s_telepon+"',"+ 
                "keterangan='"+s_keterangan+"'");

            tampilData();
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan ");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
        }
         
}//GEN-LAST:event_cmdSimpanActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
                try{
            Statement stm=cn.createStatement();
            stm.executeUpdate("DELETE FROM t_pelanggan WHERE kd_pelanggan='"+
                tabModel.getValueAt(gridProdi.getSelectedRow(),0)+"'");

            tabModel.removeRow(row);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus !");
            bersih();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        // TODO add your handling code here:
        String s_kd_pelanggan= kd_pelanggan.getText();
        String s_kategori = kategori.getSelectedItem().toString();
        String s_nama_plngn = nama_plngn.getText();
        String s_alamat = alamat.getText(); 
        String s_telepon= telepon.getText(); 
        String s_keterangan = keterangan.getText(); 
        
        //validasi isian
        if (s_kd_pelanggan.isEmpty()){
            JOptionPane.showMessageDialog(null,"Kode Pelanggan Masih Kosong");
            kd_pelanggan.requestFocus();
            return;
        }
          if (s_nama_plngn.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Pelanggan Masih Kosong");
            nama_plngn.requestFocus();
            return;
        } 
        if (s_alamat.isEmpty()){
            JOptionPane.showMessageDialog(null,"Alamat Masih Kosong");
            alamat.requestFocus();
            return;
        }
        if (s_telepon.isEmpty()){
            JOptionPane.showMessageDialog(null,"Telepon Masih Kosong");
            telepon.requestFocus();
            return;
        }
        if (s_keterangan.isEmpty()){
            JOptionPane.showMessageDialog(null,"Keterangan Masih Kosong");
            keterangan.requestFocus();
            return;
        }
      
               try{

            Statement stm=cn.createStatement();
            stm.executeUpdate("UPDATE t_pelanggan SET kd_pelanggan='"
                + s_kd_pelanggan + "',kategori='"
                + s_kategori + "',nama_plngn='"
                + s_nama_plngn + "',alamat='"
                + s_alamat + "',telepon='"
                + s_telepon + "',keterangan='"  
                + s_keterangan +"'where kd_pelanggan='"+
                tabModel.getValueAt(gridProdi.getSelectedRow(),0)+"'");
            tampilData();
            bersih();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error Update");
        }
        
         
    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_cmdCloseActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try{
            Statement stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("select * from t_pelanggan where kd_pelanggan like '%"+search.getText()+"%'");
            while (rs.next()){
                    Object[] data={rs.getString("kd_pelanggan"),
                               rs.getString ("ketegori"),           
                               rs.getString ("nama_plngn"),
                               rs.getString("alamat"), 
                               rs.getString("telepon"),
                               rs.getString("keterangan"),

                };
                tabModel.addRow(data);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataCabang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton cmdBaru;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JTable gridProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategori;
    private javax.swing.JTextField kd_pelanggan;
    private javax.swing.JTextField keterangan;
    private javax.swing.JTextField nama_plngn;
    private javax.swing.JTextField search;
    private javax.swing.JTextField telepon;
    // End of variables declaration//GEN-END:variables

}
