 

package Forms;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
 
import java.sql.*; 
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class LaporanPengeluaran extends javax.swing.JFrame {
 Connection cn= null;
 ResultSet rs = null;
 DefaultTableModel tabModel; 
 String tgl;
    
    
    public LaporanPengeluaran() {
        initComponents();
        konek();
        tampilData();  
    }
 
            void konek (){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection ("jdbc:mysql://localhost/db_multimedia_nusantara","root","");
            Object [] judul_kolom = {"Kode Pengeluaran","Tanggal","Kode Cabang","Kategori","Nama Cabang","Total"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            gridProdi.setModel(tabModel);
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();
    }
  }
    
  
   void tampilData(){
        try{
            Statement stm; //buat stm
            stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("select * from t_peng ORDER BY kd_pengeluaran ASC");//mengambil data barang
            while(rs.next()){
                Object[] data={rs.getString("kd_pengeluaran"),
                               rs.getString ("tanggal"),
                               rs.getString("kd_pelanggan"),
                               rs.getString("kategori"),
                               rs.getString("nama_plngn"),
                               rs.getString("total"),     
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    } 
    
 
    int row = 0;
 
     public void Tampil(){
      row = gridProdi.getSelectedRow();
      kd_pengeluaran.setText(tabModel.getValueAt(row, 0).toString());
     
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
      void Print() {
             try {
                 String namaFile = "report_pengeluaranbarangid.jasper";
                 HashMap parameter = new HashMap();
                 parameter.put("kd_pengeluaran",kd_pengeluaran.getText());
                 Connection kon = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_multimedia_nusantara", "root","");
                 File laporanFile = new File(namaFile);
                 
                 JasperReport jasperReport = (JasperReport)  JRLoader.loadObject(laporanFile.getPath());
                 
                 JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, kon);
                 JasperViewer.viewReport(jasperPrint, false);
                 JasperViewer.setDefaultLookAndFeelDecorated(true); 
             } catch (Exception ex) {
                 
                 JOptionPane.showMessageDialog(null, "Laporan tidak dapat dicetak!", "Cetak data", JOptionPane.ERROR_MESSAGE);
                 ex.printStackTrace();
             } 
                 
             }
    
    
       void Printtgl() {
             try {
                 String namaFile = "report_pengeluaranbarang.jasper";
                 HashMap parameter = new HashMap();
                 java.util.Date tgl=(java.util.Date) this.tanggal.getDate();
                 java.util.Date tgl2=(java.util.Date) this.tanggal2.getDate();
                 parameter.put("tanggal",new java.sql.Date(tgl.getTime()));
                 parameter.put("tanggal2",new java.sql.Date(tgl2.getTime()));
                 Connection kon = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_multimedia_nusantara", "root","");
                 File laporanFile = new File(namaFile);
                 
                 JasperReport jasperReport = (JasperReport)  JRLoader.loadObject(laporanFile.getPath());
                 
                 JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, kon);
                 JasperViewer.viewReport(jasperPrint, false);
                 JasperViewer.setDefaultLookAndFeelDecorated(true);
                 System.out.println(new java.sql.Date(tgl.getTime()));
             } catch (Exception ex) {
                 
                 JOptionPane.showMessageDialog(null, "Laporan tidak dapat dicetak!", "Cetak data", JOptionPane.ERROR_MESSAGE);
                 ex.printStackTrace();
             }
             
             }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridProdi = new javax.swing.JTable();
        cmdClose = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        kd_pengeluaran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        tanggal2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gridProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridProdiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridProdi);

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/door_out.png"))); // NOI18N
        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cari.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Cari Berdasarkan Kode Pengeluaran");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kode Pengeluaran");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Device-Printer-icon.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Laporan Pengeluaran");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("s/d");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Device-Printer-icon.png"))); // NOI18N
        jButton3.setText("Print Tanggal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(kd_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(tanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(4, 4, 4)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(btnCari)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmdClose))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kd_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(tanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCari)
                        .addComponent(cmdClose)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridProdiMouseClicked
          if (evt.getClickCount()==1) {
            Tampil();
        }
}//GEN-LAST:event_gridProdiMouseClicked

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_cmdCloseActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try{
            Statement stm=cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            rs=stm.executeQuery("select * from t_peng where kd_pengeluaran like '%"+search.getText()+"%'");
            while (rs.next()){
                      Object[] data={rs.getString("kd_pengeluaran"),
                               rs.getString ("tanggal"),
                               rs.getString("kd_pelanggan"),
                               rs.getString("kategori"),
                               rs.getString("nama_plngn"),
                               rs.getString("total"), 

                };
                tabModel.addRow(data);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Print();          
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Printtgl();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton cmdClose;
    private javax.swing.JTable gridProdi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kd_pengeluaran;
    private javax.swing.JTextField search;
    private com.toedter.calendar.JDateChooser tanggal;
    private com.toedter.calendar.JDateChooser tanggal2;
    // End of variables declaration//GEN-END:variables

}
